server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://87.251.74.126:3306/shop?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: shop
    password: kq3E-oRNlLCkMNmgZcUAwbAmZOhXnR-KxzxQkzDVI_vProENdK

  jpa:
    hibernate:
      ddl-auto: create
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
