server:
  port: 8585

logging:
  level:
    web: DEBUG

spring:
  datasource:
    url: jdbc:mysql://87.251.74.126:3306/shop?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: shop
    password: ${SHOP_PASS}

  jpa:
    hibernate:
      ddl-auto: create #create create-drop none update validate
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
